/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_mupuf_SecureFileAccess
#define DBUS_GLIB_CLIENT_WRAPPERS_org_mupuf_SecureFileAccess

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new (DBusGProxy *proxy, const char * IN_title, char ** OUT_fileuri, gboolean* OUT_hasfile, GError **error)

{
  return dbus_g_proxy_call (proxy, "GtkSandboxFileChooserDialogNew", error, G_TYPE_STRING, IN_title, G_TYPE_INVALID, G_TYPE_STRING, OUT_fileuri, G_TYPE_BOOLEAN, OUT_hasfile, G_TYPE_INVALID);
}

typedef void (*org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new_reply) (DBusGProxy *proxy, char * OUT_fileuri, gboolean OUT_hasfile, GError *error, gpointer userdata);

static void
org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_fileuri;
  gboolean OUT_hasfile;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_fileuri, G_TYPE_BOOLEAN, &OUT_hasfile, G_TYPE_INVALID);
  (*(org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new_reply)data->cb) (proxy, OUT_fileuri, OUT_hasfile, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new_async (DBusGProxy *proxy, const char * IN_title, org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GtkSandboxFileChooserDialogNew", org_mupuf_SecureFileAccess_gtk_sandbox_file_chooser_dialog_new_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_title, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_mupuf_SecureFileAccess */

G_END_DECLS
